### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by ollivera** [CleverbotIO/rust-cleverbot.io#7]
Hi, I tried to run it with rust 1.8 and I got the error below:

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Ssl(OpenSslErrors([UnknownError { library: "SSL routines", function: "SSL23_GET_SERVER_HELLO", reason: "sslv3 alert handshake failure" }])))', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Process didn't exit successfully: `target/release/clever` (exit code: 101)

**Comment by elifoster** [comment]
Are you on OSX?

**Comment by ollivera** [comment]
Hi, actually it doesn't seem a rust-cleverbot bug. I tried in a different server and it worked. 
So it worked in my Ubuntu server and it didn't work in my CentOS server. I upgraded openssl library but it didn't help.
I have the same version in both: OpenSSL 1.0.1g 7 Apr 2014

I suspect that something is misconfigured in my CentOS server

**Comment by elifoster** [comment]
I get a similar error when running on OSX, but following the steps described at hyperium/hyper#553 resolves it. I suspect there's something similar for CentOS, or maybe it's the same issue :smile:

**Comment by ollivera** [comment]
Hi, I am running it in CentOS. If you upgrade Hyper version it will work, it is probably due some internal hyper ssl support added recently.
So, please bump hyper to the latest! :)
